using Microsoft.EntityFrameworkCore;
using SecretShareApi.Controllers.DataTransferObjects;
using SecretShareApi.Entities;
using SecretShareApi.Queries.SebasDbContext;
using SecretShareApi.SupportingClasses;

namespace SecretShareApi.Repositories
{
    public class SharedSecretRepository
    {
        private readonly SebasDbContext _sebasDbContext;
        private readonly IConfiguration _config;
        private readonly EncryptionService _encryptionService;

        public SharedSecretRepository(
            SebasDbContext sebasDbContext,
            IConfiguration config,
            EncryptionService encryptionService)
        {
            _sebasDbContext = sebasDbContext;
            _config = config;
            _encryptionService = encryptionService;
        }

        public virtual IQueryable<SharedSecret> SharedSecrets => _sebasDbContext.SharedSecrets;

        /// Encrypts a secret and sets the lifetime, stores the secret. Creates a token and url to retrieve the secret
        public virtual async Task<string> EncryptAndSaveSecret(StoreSecretDto dto)
        {
            // Trim whitespace
            var trimmedSecret = dto.Secret.Trim();
            var trimmedPhrase = dto.Passphrase.Trim();

            // Encrypt the secret using the given passphrase as secret KEY and IV
            var hash = _encryptionService.Encrypt(trimmedSecret, trimmedPhrase);

            // Add the lifetime to the current time to get the moment when the secret expires
            DateTime expire = DateTime.UtcNow.AddSeconds(dto.Lifetime);

            // Create a hash from the passphrase, this is stored in the database and will be used to compare to the hash generated by the receiver of the secret
            var token = _encryptionService.ComputeSha256Hash(dto.Passphrase);

            // Create Guid to add to url this will be used make the combination of secret and url unique
            var addUrl = _encryptionService.ComputeSha256Hash(Guid.NewGuid().ToString());
            var url = _config.GetValue<string>("PasswordShare:PickUpUrl") + "/" + addUrl;

            SharedSecret secret = new SharedSecret
            {
                Secret = hash,
                Expire = expire,
                Token = token,
                Urlextension = addUrl
            };

            _sebasDbContext.Add(secret);
            await _sebasDbContext.SaveChangesAsync();

            return url;
        }

        
        /// Checks if the passphrase is correct by matching it to token of SharedSecret then retrieves, decrypt's and deletes the secret
        public virtual async Task<string> VerifyAndDecryptSecret(RetrieveSecretDto dto)
        {
            var secret = "";

            // Hash the passphrase, this will be checked against the value of Token in de database
            var hashphrase = _encryptionService.ComputeSha256Hash(dto.Passphrase);
            var urlExtension = dto.UrlExtension;

            // Retrieve encrypted password
            var hashword = await SharedSecrets
                .FilterByUrlExtension(urlExtension)
                .SingleOrDefaultAsync();

            if (hashword == null)
            {
                return secret;
            }

            if (hashword.Expire < DateTime.UtcNow)
            {
                // Secret has expired but was not yet cleaned up, remove it and treat as not found
                _sebasDbContext.Entry(hashword).State = EntityState.Deleted;
                await _sebasDbContext.SaveChangesAsync();

                return secret;
            }

            if (hashword.Token != hashphrase) //TODO: unit test
            {
                // If the given pasphrase does not match up the count of tries and delete the secret if tries exceeds three
                hashword.Tries ++;
                if (hashword.Tries > 3)
                {
                    _sebasDbContext.Entry(hashword).State = EntityState.Deleted;                    
                }

                await _sebasDbContext.SaveChangesAsync();

                return secret;
            }

            // Decrypt password
            secret = _encryptionService.Decrypt(hashword.Secret, dto.Passphrase);

            // Remove entry from the Database
            _sebasDbContext.Entry(hashword).State = EntityState.Deleted;
            await _sebasDbContext.SaveChangesAsync();

            return secret;
        }
    }
}

